In [17]:
from pathlib import Path
import sys
import numpy as np

current_dir = Path.cwd()
sys.path.append(str(current_dir.parent.parent))


from dataloader import DataLoader_
from src.utils.ControlChart.control_chart import DFUC
from src.models.ysl23 import YSL23 as MF
from src.utils.Filters import ARFilter

In [10]:
data_loader = DataLoader_(exp_type="KolektorSDD")

In [11]:
it = iter(data_loader)       # this should NOT raise
data = next(it)       # should print 1

In [12]:
data.shape

(399, 720896)

In [19]:
n_ar = 0
n_manifold = 330
n_cc = 17

m0,m1,m2 = n_manifold,n_ar if n_ar is not None else 0, n_cc
n_oc = data.shape[0] - m0-m1-m2

In [20]:
scales = 1
keep_mask = np.ones(data.shape[1], dtype=bool)

data = data/scales
data = data[:,keep_mask]

manifold_data = data[:m0]
ar_data = data[m0:m0+m1]
cc_data = data[m0+m1:m0+m1+m2]
oc_data = data[-n_oc:]

In [21]:
mf_constants = [1100,700,1100]
c0,c1,c2 = mf_constants
sigma = 0.0808
mf = MF(manifold_data, c0=c0, c1=c1,c2=c2,d=None,estimate_sig=False,sigma = sigma)

In [23]:
m1 = 0 
transformed_data = mf.deviations(ar_data) if m1 > 0 else np.empty((0, 1))
ar_model = ARFilter(transformed_data,max_p=20)

In [9]:
data_loader = DataLoader_(exp_type="TE",N=10,amplitude=0)
it = iter(data_loader)       # this should NOT raise
print(next(it))         # should print 1
print(next(it))  
print(next(it).shape)  

[[45.        45.        45.        ... 46.430527  35.865322  12.930642 ]
 [45.0014    44.996758  44.981747  ... 46.4473    35.92414   12.215758 ]
 [44.99646   45.000187  44.996223  ... 46.410038  35.856625  13.6952715]
 ...
 [44.99445   45.0054    45.011932  ... 46.44139   36.11101   13.11666  ]
 [45.005188  45.01491   45.00267   ... 46.45346   35.88832   11.7483835]
 [44.98684   45.014202  45.008198  ... 46.442593  35.948624  10.975139 ]]
[[45.       45.       45.       ... 46.430527 35.865322 12.930642]
 [45.00856  45.00427  44.998768 ... 46.447716 36.09882  12.812065]
 [45.002514 45.005142 45.005684 ... 46.424755 35.85829   9.128983]
 ...
 [44.985825 44.98864  44.982445 ... 46.429546 35.925655 11.382841]
 [44.99514  45.003597 44.998756 ... 46.44417  35.886833 11.733305]
 [44.998985 45.005157 45.005264 ... 46.4414   35.871017 13.302742]]
(1441, 390)


In [5]:
data_loader = DataLoader_(exp_type="SyntheticProcess",fault_no=4,amplitude=0,N=10)
for idx, data in enumerate(data_loader):
    print(data)

[[ 4.92928849e-01 -1.04956547e-01 -6.72204566e-01  1.87349238e-02
  -1.23435415e-01  1.05134282e-02]
 [ 7.58767343e-01 -2.59472160e-01 -5.51505242e-01 -2.26531123e-01
   2.34963762e-02 -9.97210281e-02]
 [ 5.54206571e-01  2.08316142e-01 -1.12054081e+00  4.89547102e-02
   6.41860138e-02  2.33037563e-02]
 ...
 [ 6.59835555e-01  8.85654642e-01 -8.03396316e-02 -2.37201064e-01
  -5.06225424e-02 -1.08426746e-01]
 [ 4.06031755e-01  1.12793265e+00  3.75255822e-04 -5.36447250e-02
   1.28524081e-02 -6.87543263e-02]
 [ 1.72206551e-01  8.94969459e-01  3.14263705e-01  9.11167974e-02
   1.43181033e-01  1.26486181e-02]]
[[ 0.06944056 -0.32731827 -0.84496904  0.08005223 -0.01867981  0.16283578]
 [ 0.24994604 -0.48787495 -0.75704911 -0.18397741 -0.04882984  0.07033753]
 [-0.01801936 -0.98230556 -0.40433238  0.11937594  0.05854919  0.06803764]
 ...
 [ 0.35392248  0.48679694 -0.39239762  0.01861328 -0.0422738   0.09864194]
 [ 0.3807863   0.7567285  -0.50229299  0.06951905  0.10645488  0.08763305]
 [-0.067

In [22]:
class MyLoader(DataLoader_):
    def __init__(self, N: int):
        super().__init__()   # parent expects something, pass dummy
        self.N = N
    def __len__(self):
        return self.N
    def get_item(self, idx):
        # you decide what to return — here, just return constant `1`
        return 1

    
data_loader = MyLoader(N=100)

In [23]:
data_loader.N

100

In [19]:
data_loader.amplitude
data_loader.N = 100

In [ ]:
it = iter(data_loader) 
print(next(it))         # should print 1
print(next(it))  

1
1


AttributeError: 'int' object has no attribute 'shape'